name: Cypress Tests on PRs

on:
  push:
    branches:
      - review

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        container: [1, 2, 3]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Start application
        run: npm start &
        run: sleep 10

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          group: ${{ matrix.container }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
