name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      SERVER_PORT: 5500
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' 

      - name: Install dependencies
        run: npm install

      - name: Verify Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Build the project
        run: npm run build

      - name: Start server
        run: |
          npm start > server.log 2>&1 &
          echo "Waiting for server to start..."
          while ! nc -z localhost $SERVER_PORT; do
            sleep 10
            cat server.log  # Output server logs for debugging
          done
          echo "Server started!"

      - name: Run tests
        run: |
          export CYPRESS_baseUrl=http://localhost:$SERVER_PORT
          npm test